"""
Page 2 — CRM Tickets (Admin Only)

View and manage leads created by the chat agent.
Admins can:
- View all lead tickets
- Update status (new → contacted → qualified → closed)
- Filter by status
- See rich Arabic lead details
"""

import streamlit as st
import re
import textwrap
from datetime import datetime

st.set_page_config(
    page_title="CRM Tickets — Kayfa",
    page_icon="📋",
    layout="wide",
)

from pathlib import Path
from core.auth import require_auth, require_admin
from core.db import get_leads_collection
from sidebar_helper import render_sidebar

LOGO_PATH = Path(__file__).resolve().parent.parent / "logo.png"

require_auth()
require_admin()

render_sidebar()

st.title("📋 CRM Tickets")
st.caption("Manage leads generated by the sales agent.")
st.markdown("---")

# Custom CSS for Lead Display Cards
st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;600;700&family=Inter:wght@300;400;500;600;700&display=swap');

    .stApp, .stApp [data-testid="stHeader"] {
        font-family: 'Inter', 'Cairo', 'Segoe UI', Tahoma, sans-serif !important;
    }

    /* Lead Card Layout */
    .lead-card {
        background-color: #ffffff;
        border: 1px solid rgba(0, 0, 0, 0.08);
        border-radius: 12px;
        padding: 20px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px -1px rgba(0, 0, 0, 0.01);
        margin-bottom: 16px;
        font-family: 'Inter', 'Cairo', sans-serif;
    }

    .lead-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 1px solid rgba(0, 0, 0, 0.05);
        padding-bottom: 10px;
        margin-bottom: 15px;
    }

    .lead-title {
        font-size: 1.15rem;
        font-weight: 700;
        color: #1e293b;
        margin: 0;
        display: flex;
        align-items: center;
        gap: 10px;
    }

    .lead-meta-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
        gap: 12px;
        margin-bottom: 15px;
    }

    .lead-item {
        display: flex;
        flex-direction: column;
        gap: 4px;
        unicode-bidi: plaintext;
        text-align: start;
    }

    .lead-label {
        font-size: 0.85rem;
        font-weight: 700;
        color: #64748b;
    }

    .lead-val {
        font-size: 0.95rem;
        color: #334155;
        font-weight: 500;
    }

    /* Info Blocks */
    .lead-box {
        margin-top: 12px;
        padding: 12px 16px;
        border-radius: 8px;
        font-size: 0.95rem;
        line-height: 1.6;
        border-left: 4px solid;
        unicode-bidi: plaintext;
        text-align: start;
    }

    .lead-box-title {
        font-weight: 700;
        margin-bottom: 4px;
        font-size: 0.85rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }

    .lead-box.summary {
        background-color: #f0f7ff;
        border-left-color: #3b82f6;
        color: #1e40af;
    }
    .lead-box.summary .lead-box-title {
        color: #2563eb;
    }

    .lead-box.signals {
        background-color: #ecfdf5;
        border-left-color: #10b981;
        color: #065f46;
    }
    .lead-box.signals .lead-box-title {
        color: #059669;
    }

    .lead-box.objections {
        background-color: #fffbeb;
        border-left-color: #f59e0b;
        color: #78350f;
    }
    .lead-box.objections .lead-box-title {
        color: #d97706;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# Filters
status_filter = st.selectbox(
    "Filter by status",
    options=["All", "new", "contacted", "qualified", "closed"],
    index=0,
)

# Fetch leads
coll = get_leads_collection()
query = {}
if status_filter != "All":
    query["status"] = status_filter

leads = list(coll.find(query).sort("created_at", -1))

st.write(f"**{len(leads)}** tickets found")

if not leads:
    st.info("No tickets match the selected filter.")
else:
    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    status_counts = {"new": 0, "contacted": 0, "qualified": 0, "closed": 0}
    for lead in leads:
        status_counts[lead.get("status", "new")] = status_counts.get(lead.get("status", "new"), 0) + 1

    with col1:
        st.metric("New", status_counts.get("new", 0))
    with col2:
        st.metric("Contacted", status_counts.get("contacted", 0))
    with col3:
        st.metric("Qualified", status_counts.get("qualified", 0))
    with col4:
        st.metric("Closed", status_counts.get("closed", 0))

    st.markdown("---")

    def _temperature_badge(temp: str) -> str:
        temp_map = {
            "ساخن": ("🔥", "#dc2626"),
            "دافئ": ("🌡️", "#ea580c"),
            "بارد": ("❄️", "#2563eb"),
        }
        icon, color = temp_map.get(temp, ("•", "#6b7280"))
        return f"<span style='background:{color};color:white;padding:2px 8px;border-radius:12px;font-size:0.85em;'>{icon} {temp or 'N/A'}</span>"

    # Display leads
    for lead in leads:
        status_color = {
            "new": "🔵",
            "contacted": "🟡",
            "qualified": "🟢",
            "closed": "⚪",
        }.get(lead.get("status", "new"), "⚪")

        products = lead.get("products") or lead.get("interest", "N/A")
        ticket_id = lead.get("ticket_id", "—")
        temp_badge = _temperature_badge(lead.get("temperature", ""))

        # Dynamic LTR/RTL detection based on lead details
        is_arabic = bool(re.search(r'[\u0600-\u06FF]', lead.get('conversation_summary', '') or lead.get('name', '')))
        card_dir = "rtl" if is_arabic else "ltr"
        card_align = "right" if is_arabic else "left"

        # Dynamically translated labels
        labels = {
            "products": "المنتجات" if is_arabic else "Products",
            "city": "المدينة" if is_arabic else "City",
            "dialect": "اللغة / اللهجة" if is_arabic else "Language / Dialect",
            "goal": "الهدف" if is_arabic else "Goal",
            "level": "المستوى" if is_arabic else "Level",
            "next_action": "الإجراء التالي" if is_arabic else "Next Action",
            "summary": "ملخص المحادثة" if is_arabic else "Conversation Summary",
            "signals": "إشارات الشراء" if is_arabic else "Buying Signals",
            "objections": "الاعتراضات / المعالجة" if is_arabic else "Objections / Resolution",
        }

        html_content = (
            f'<div class="lead-card" dir="{card_dir}" style="text-align: {card_align};">'
            f'<div class="lead-header">'
            f'<h3 class="lead-title" style="margin:0;">'
            f'{lead.get("name", "N/A")} &nbsp; {temp_badge}'
            f'</h3>'
            f'<span style="font-family: monospace; font-size: 0.85rem; color: #64748b;">ID: {ticket_id}</span>'
            f'</div>'
            f'<div class="lead-meta-grid">'
            f'<div class="lead-item">'
            f'<span class="lead-label">{labels["products"]}</span>'
            f'<span class="lead-val">{products}</span>'
            f'</div>'
            f'<div class="lead-item">'
            f'<span class="lead-label">{labels["city"]}</span>'
            f'<span class="lead-val">{lead.get("city") or "—"}</span>'
            f'</div>'
            f'<div class="lead-item">'
            f'<span class="lead-label">{labels["dialect"]}</span>'
            f'<span class="lead-val">{lead.get("language_dialect") or "—"}</span>'
            f'</div>'
            f'<div class="lead-item">'
            f'<span class="lead-label">{labels["goal"]}</span>'
            f'<span class="lead-val">{lead.get("goal") or "—"}</span>'
            f'</div>'
            f'<div class="lead-item">'
            f'<span class="lead-label">{labels["level"]}</span>'
            f'<span class="lead-val">{lead.get("level") or "—"}</span>'
            f'</div>'
            f'<div class="lead-item">'
            f'<span class="lead-label">{labels["next_action"]}</span>'
            f'<span class="lead-val">{lead.get("next_action") or "—"}</span>'
            f'</div>'
            f'</div>'
            f'<div class="lead-box summary">'
            f'<div class="lead-box-title">{labels["summary"]}</div>'
            f'<div>{lead.get("conversation_summary") or lead.get("notes") or "—"}</div>'
            f'</div>'
            f'<div class="lead-box signals">'
            f'<div class="lead-box-title">{labels["signals"]}</div>'
            f'<div>{lead.get("buying_signals") or "—"}</div>'
            f'</div>'
            f'<div class="lead-box objections">'
            f'<div class="lead-box-title">{labels["objections"]}</div>'
            f'<div>{lead.get("objections") or "—"}</div>'
            f'</div>'
            f'</div>'
        )

        with st.expander(
            f"{status_color} {ticket_id} — {lead.get('name', 'Unknown')} — {products} "
            f"({lead.get('status', 'new')})",
            expanded=False,
        ):
            col_left, col_right = st.columns([3, 1])

            with col_left:
                st.markdown(textwrap.dedent(html_content), unsafe_allow_html=True)

            with col_right:
                st.write(f"**Phone:** {lead.get('phone', lead.get('contact', 'N/A'))}")
                st.write(f"**Email:** {lead.get('email', 'N/A')}")
                st.write(f"**Preferred contact:** {lead.get('preferred_contact', 'N/A')}")
                st.write(f"**Created:** {lead.get('created_at', 'N/A')}")
                st.write(f"**Source:** {lead.get('source', 'N/A')}")

                new_status = st.selectbox(
                    "Update status",
                    options=["new", "contacted", "qualified", "closed"],
                    index=["new", "contacted", "qualified", "closed"].index(
                        lead.get("status", "new")
                    ),
                    key=f"status_{lead['_id']}",
                )
                if st.button("Update", key=f"update_{lead['_id']}", use_container_width=True):
                    coll.update_one(
                        {"_id": lead["_id"]},
                        {"$set": {"status": new_status, "updated_at": datetime.utcnow().isoformat()}}
                    )
                    st.success(f"Status updated to '{new_status}'")
                    st.rerun()

                if st.button("Delete", key=f"delete_{lead['_id']}", use_container_width=True, type="secondary"):
                    coll.delete_one({"_id": lead["_id"]})
                    st.warning("Lead deleted")
                    st.rerun()
